---

ZAZAR0094DPEPL00101:
  hostname: 192.168.204.196
  platform: huawei
  groups:
    - huawei
  data:
    site: '0094'

ZAZAR0094DPEPL00102:
  hostname: 192.168.204.197
  platform: huawei
  groups:
    - huawei
  data:
    site: '0094'

ZAZAR0094DPEPL00103:
  hostname: 192.168.204.198
  platform: huawei
  groups:
    - huawei
  data:
    site: '0094'

ZAZAR0094DPEPL00104:
  hostname: 192.168.204.199
  platform: huawei
  groups:
    - huawei
  data:
    site: '0094'

ZAZAR0094DPEPL00105:
  hostname: 192.168.204.200
  platform: ios
  groups:
    - ios
  data:
    site: '0094'

#ZAZAR0094DPEPL00106:
#  hostname: 192.168.204.201
#  platform: ios
#  groups:
#    - ios
#  data:
#    site: '0094'

ZAZAR0094DPEPL00107:
  hostname: 192.168.204.202
  platform: ios
  groups:
    - ios
  data:
    site: '0094'



ZSZAR0535MSHPL02401:
  hostname: 192.168.207.59
  platform: ios
  groups:
    - ios
  data:
    site: '0535'

ZSZAR0535MSHPL02101:
  hostname: 192.168.207.57
  platform: ios
  groups:
    - ios
  data:
    site: '0535'

ZSZAR0535MSHPL02301:
  hostname: 192.168.207.58
  platform: ios
  groups:
    - ios
  data:
    site: '0535'

ZSZAR0535MSHPL00401:
  hostname: 192.168.207.47
  platform: ios
  groups:
    - ios
  data:
    site: '0535'
